backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

locale: 'fr'

collections:
  - name: "posts"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    preview_path: "articles/{{slug}}.html"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Résumé", name: "summary", widget: "text" }
      - { label: "Image de couverture", name: "thumbnail", widget: "image" }
      - { label: "Brouillon", name: "draft", widget: "boolean", default: false }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "À propos"
        name: "a-propos"
        file: "a-propos.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
      - label: "Contact"
        name: "contact"
        file: "contact.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
